<#
.SYNOPSIS
    Phase 1 of the documentation migration: inventory, backlog candidates and
    the link graph. Read-only — it writes only under .migration/.

.DESCRIPTION
    The documentation grew cumulatively and now mixes canon, specification,
    architecture, guidelines, decisions, runtime content and live task lists.
    Before anything is moved or deleted, this records what exists, which
    documents carry backlog or open questions, and how they reference each
    other. Nothing here classifies or migrates: classification is a judgement
    call and must be reviewable against this inventory.

    Idempotent: rerunning overwrites the three reports and nothing else.

.PARAMETER OutputDirectory
    Where the reports are written. Defaults to .migration/ at the repo root.

.EXAMPLE
    pwsh ./scripts/docs/inventory.ps1
#>
[CmdletBinding()]
param(
    [string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
if (-not $OutputDirectory) { $OutputDirectory = Join-Path $repoRoot '.migration' }
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

# Documentation lives in four places: docs/, the repo root, the canonical
# agent-context root, and its generated mirrors. Mirrors are inventoried but
# flagged, because editing them by hand is forbidden — they are regenerated by
# scripts/Sync-AgentContext.ps1.
$roots = @(
    @{ Path = 'docs';    Kind = 'documentation' },
    @{ Path = '.agents'; Kind = 'agent-context-canonical' },
    @{ Path = '.claude'; Kind = 'agent-context-mirror' },
    @{ Path = '.codex';  Kind = 'agent-context-mirror' },
    @{ Path = '.github'; Kind = 'github-config' }
)

# Words that mark a block as future work rather than description.
$backlogMarkers = @(
    'TODO', 'FIXME', 'pending', 'pendiente', 'backlog', 'roadmap', 'milestone',
    'vertical slice', 'next step', 'próximo paso', 'proximo paso', 'por definir',
    'por implementar', 'to implement', 'future', 'futuro', 'deferred', 'diferido',
    'not yet', 'todavía no', 'todavia no', 'queda pendiente', 'owed'
)
$questionMarkers = @(
    'open question', 'pregunta abierta', 'unresolved', 'sin resolver',
    'to decide', 'por decidir', 'undecided', 'needs a decision', 'TBD'
)

function Get-DocRecord {
    param([System.IO.FileInfo]$File, [string]$Kind)

    $relative = [IO.Path]::GetRelativePath($repoRoot, $File.FullName).Replace('\', '/')
    $text = Get-Content -LiteralPath $File.FullName -Raw -ErrorAction SilentlyContinue
    if ($null -eq $text) { $text = '' }
    $lines = $text -split "`r?`n"

    # First ATX heading wins; fall back to the file name.
    $title = ($lines | Where-Object { $_ -match '^\s{0,3}#\s+\S' } | Select-Object -First 1)
    if ($title) { $title = ($title -replace '^\s{0,3}#\s+', '').Trim() }
    else { $title = $File.BaseName }

    $backlogHits = @()
    $questionHits = @()
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        # Whole words only. Substring matching counted "deferred disposal" as
        # backlog, "future attachments" as a plan, and found "owed" inside
        # "allowed" and "reflowed" — which is how docs/engineering/architecture.md was
        # accused of being half roadmap when it is a description throughout.
        foreach ($marker in $backlogMarkers) {
            if ($line -match ('\b' + [regex]::Escape($marker) + '\b')) {
                $backlogHits += [pscustomobject]@{ line = $i + 1; marker = $marker; text = $line.Trim() }
                break
            }
        }
        foreach ($marker in $questionMarkers) {
            if ($line -match ('\b' + [regex]::Escape($marker) + '\b')) {
                $questionHits += [pscustomobject]@{ line = $i + 1; marker = $marker; text = $line.Trim() }
                break
            }
        }
        # Unchecked task boxes are backlog by construction.
        if ($line -match '^\s*[-*]\s+\[ \]\s+\S') {
            $backlogHits += [pscustomobject]@{ line = $i + 1; marker = 'unchecked-task'; text = $line.Trim() }
        }
    }

    # Code first, links second. `MIGRATIONS[v](data)` inside a fenced block is
    # valid Python and not a markdown link; counting it produced five phantom
    # broken links in the first inventory, all pointing at a file named `data`.
    $prose = [regex]::Replace($text, '(?ms)^\s*```.*?^\s*```', '')
    $prose = [regex]::Replace($prose, '`[^`\r\n]*`', '')

    $links = @()
    foreach ($m in [regex]::Matches($prose, '\[[^\]]*\]\(([^)\s]+)')) {
        $target = $m.Groups[1].Value
        if ($target -match '^(https?:|mailto:|#)') { continue }
        $links += $target
    }

    [pscustomobject]@{
        path                  = $relative
        title                 = $title
        root_kind             = $Kind
        bytes                 = $File.Length
        lines                 = $lines.Count
        has_front_matter      = $text.StartsWith('---')
        headings              = (($lines | Where-Object { $_ -match '^\s{0,3}#{1,6}\s+\S' }) | Measure-Object).Count
        contains_backlog      = $backlogHits.Count -gt 0
        backlog_hit_count     = $backlogHits.Count
        backlog_hits          = @($backlogHits | Select-Object -First 40)
        contains_open_questions = $questionHits.Count -gt 0
        open_question_hits    = @($questionHits | Select-Object -First 20)
        outbound_links        = @($links | Sort-Object -Unique)
        # Left for the classification pass; recorded as nulls so the schema is
        # stable and a reviewer can see what is still undecided.
        proposed_type         = $null
        authority             = $null
        domains               = @()
        duplicates_or_overlaps = @()
        related_code          = @()
        proposed_destination  = $null
        action                = 'undecided'
    }
}

$records = @()
foreach ($root in $roots) {
    $full = Join-Path $repoRoot $root.Path
    if (-not (Test-Path $full)) { continue }
    foreach ($file in Get-ChildItem $full -Recurse -File -Include *.md, *.txt, *.json, *.yml, *.yaml -ErrorAction SilentlyContinue) {
        # Agent worktrees are disposable checkouts, not documentation. They
        # duplicate every doc and would drown the link graph in false edges.
        if ($file.FullName -match '[\\/]worktrees[\\/]') { continue }
        $records += Get-DocRecord -File $file -Kind $root.Kind
    }
}
foreach ($file in Get-ChildItem $repoRoot -File -Filter *.md) {
    $records += Get-DocRecord -File $file -Kind 'repo-root'
}

$records = $records | Sort-Object path

# --- Reports -------------------------------------------------------------

$inventoryPath = Join-Path $OutputDirectory 'document-inventory.json'
$records | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $inventoryPath -Encoding UTF8

$backlogPath = Join-Path $OutputDirectory 'backlog-candidates.json'
$records |
    Where-Object { $_.contains_backlog -or $_.contains_open_questions } |
    ForEach-Object {
        [pscustomobject]@{
            source_document      = $_.path
            title                = $_.title
            backlog_hit_count    = $_.backlog_hit_count
            backlog_hits         = $_.backlog_hits
            open_question_hits   = $_.open_question_hits
            # Filled by the classification pass, not inferred here: turning a
            # speculative paragraph into an issue with invented acceptance
            # criteria is the failure mode this migration must avoid.
            proposed_issue_title = $null
            type                 = $null
            area                 = $null
            action               = 'undecided'
        }
    } |
    ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $backlogPath -Encoding UTF8

# Link graph, with the broken edges called out — a restructure cannot start
# without knowing which references are already dangling.
$known = [System.Collections.Generic.HashSet[string]]::new()
foreach ($r in $records) { [void]$known.Add($r.path) }

$edges = @()
foreach ($r in $records) {
    foreach ($link in $r.outbound_links) {
        $clean = ($link -split '#')[0]
        if ([string]::IsNullOrWhiteSpace($clean)) { continue }
        $resolved = [IO.Path]::GetFullPath(
            (Join-Path (Split-Path (Join-Path $repoRoot $r.path)) $clean))
        $relative = [IO.Path]::GetRelativePath($repoRoot, $resolved).Replace('\', '/')
        $edges += [pscustomobject]@{
            from    = $r.path
            to_raw  = $link
            to      = $relative
            exists  = (Test-Path -LiteralPath $resolved)
        }
    }
}
$linksPath = Join-Path $OutputDirectory 'document-links.json'
$edges | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $linksPath -Encoding UTF8

# --- Summary -------------------------------------------------------------

$broken = @($edges | Where-Object { -not $_.exists })
[pscustomobject]@{
    Documents          = $records.Count
    WithBacklog        = @($records | Where-Object { $_.contains_backlog }).Count
    WithOpenQuestions  = @($records | Where-Object { $_.contains_open_questions }).Count
    WithFrontMatter    = @($records | Where-Object { $_.has_front_matter }).Count
    Links              = $edges.Count
    BrokenLinks        = $broken.Count
} | Format-List

if ($broken.Count -gt 0) {
    "`nBroken links:"
    $broken | ForEach-Object { "  {0} -> {1}" -f $_.from, $_.to_raw }
}

"`nWrote:"
"  $inventoryPath"
"  $backlogPath"
"  $linksPath"
