#nullable enable
using System;
using System.Collections.Generic;

namespace WorldofGoses.Domain;

public static class FounderNarrativeCatalog
{
    public static IReadOnlyList<FounderNarrativeQuestion> Questions { get; } =
        Array.AsReadOnly(new[]
        {
            Q("hand", "La mano que se aleja",
                "El camino se parte entre ambos.\nLa otra figura comienza a alejarse, arrastrada hacia una oscuridad distinta.\nSolo queda tiempo para un movimiento.", 0f,
                O("hold", "Aferrarme a su mano mientras todavía pueda sentirla.",
                    "La presión dura un instante más. Después, la distancia vuelve a crecer.",
                    "Recordaste el último contacto.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Strength), 2),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Protective), 2),
                    C(FounderScoreAxis.Attachment, "Bond", 2),
                    C(FounderScoreAxis.RiskProfile, "Bold", 1)),
                O("observe", "Observar la dirección, la distancia y cada cambio de la fractura.",
                    "La separación continúa, pero su trayectoria queda grabada.",
                    "Conservaste la dirección de la fractura.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Observation), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 2),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Reflective), 1),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1)),
                O("stabilise", "Intentar estabilizar el camino antes de que termine de dividirse.",
                    "Los bordes obedecen durante un pulso. No es suficiente, pero fue real.",
                    "Intentaste reparar el camino roto.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.ManualPrecision), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Disciplined), 2),
                    C(FounderScoreAxis.Control, "Structured", 2),
                    C(FounderScoreAxis.Lineage, LineageId.Kovari.Value, 1)),
                O("call", "Hacer que escuche dónde intentaré volver a encontrarle.",
                    "Tu intención atraviesa la fractura, aunque no sabes qué parte llegó.",
                    "Dejaste un lugar posible para el reencuentro.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Memory), 2),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Tenacious), 2),
                    C(FounderScoreAxis.LeadershipStyle, "Connective", 2),
                    C(FounderScoreAxis.Lineage, LineageId.Theryn.Value, 1))),

            Q("word", "La palabra que no termina",
                "Su voz todavía logra atravesar la fractura, pero las palabras llegan deformadas.\nSolo una parece conservar significado.", 0f,
                O("find", "«Encuéntrame.»", "La palabra se convierte en dirección, aunque no promete llegada.", "Creíste escuchar: «Encuéntrame».",
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Tenacious), 2),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1)),
                O("return", "«Regresa.»", "Algo en ti se orienta hacia lo perdido.", "Creíste escuchar: «Regresa».",
                    C(FounderScoreAxis.Attachment, "Return", 2),
                    C(FounderScoreAxis.IdentityContinuity, "Continuity", 2),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Protective), 1)),
                O("remember", "«Recuerda.»", "Los recuerdos dejan de ser ruido y se aferran unos a otros.", "Creíste escuchar: «Recuerda».",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Memory), 3),
                    C(FounderScoreAxis.Contemplation, "Reflective", 2),
                    C(FounderScoreAxis.Lineage, LineageId.Caelith.Value, 1)),
                O("continue", "«Continúa.»", "La fractura ya no parece una orden de detenerte.", "Creíste escuchar: «Continúa».",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Adaptability), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Independent), 2),
                    C(FounderScoreAxis.Autonomy, "Autonomous", 2))),

            Q("detail", "El último detalle intacto",
                "Su silueta desaparece.\nLa memoria permanece, pero ya no puede conservarlo todo con la misma claridad.\nUn detalle se niega a desvanecerse.", 0f,
                O("name", "La forma en que pronunciaba mi nombre.", "Tu identidad adquiere un borde al ser recordada por otra voz.", "La forma en que pronunciaba tu nombre permaneció intacta.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Memory), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Reflective), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Myrven.Value, 1)),
                O("hands", "El movimiento de sus manos cuando reparábamos algo juntos.", "Un gesto repetido reconstruye la idea de una obra compartida.", "Recordaste sus manos reparando algo junto a las tuyas.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.ManualPrecision), 3),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.EngineeringManufacturing), 3),
                    C(FounderScoreAxis.Lineage, LineageId.Kovari.Value, 1)),
                O("object", "El peso del objeto que ambos reconocíamos como nuestro.", "La memoria del objeto introduce una palabra nueva: peso.", "Conservaste el peso de aquello que ambos llamaban suyo.",
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.Logistics), 2),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Cooperative), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Orveth.Value, 1)),
                O("journey", "La sensación de avanzar juntos sin conocer el destino.", "El destino desaparece; el movimiento compartido no.", "Recordaste avanzar juntos sin conocer el destino.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Adaptability), 3),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.ExplorationSurvival), 3),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1))),

            Q("old-form", "La forma que queda atrás",
                "Dejas de sentir rostro, manos y respiración.\nTu antigua forma ya no puede acompañarte.\nAferrarte a ella podría arrastrar consigo lo que todavía permanece.", 0f,
                O("exact", "Conservar su forma exacta mientras sea posible.", "La forma resiste como un contorno bajo presión.",
                    C(FounderScoreAxis.IdentityContinuity, "Exact", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Tenacious), 2),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Devout), 1)),
                O("sensation", "Conservar únicamente las sensaciones que alguna vez produjo.", "El contorno desaparece; la sensibilidad queda.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Empathy), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Compassionate), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Eirune.Value, 1)),
                O("separate", "Separar mi identidad de cualquier cuerpo que haya tenido.", "La identidad permanece sin necesitar una silueta.",
                    C(FounderScoreAxis.Autonomy, "Independent", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Independent), 3),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Secular), 2)),
                O("release", "Permitir que desaparezca para poder adoptar algo nuevo.", "La antigua forma se disuelve sin llevarse la memoria.",
                    C(FounderScoreAxis.TransformationAcceptance, "Open", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Restless), 3),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Syncretic), 2))),

            Q("time", "El tiempo adquiere orden",
                "Antes, todos tus recuerdos podían existir al mismo tiempo.\nAhora comienzan a colocarse unos detrás de otros.\nPara conservarlos debes aceptar una manera de ordenarlos.", 0f,
                O("cause", "Por aquello que ocurrió primero y lo que provocó después.", "Los recuerdos forman una cadena de causas.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Observation), 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.ResearchEducation), 3),
                    C(FounderScoreAxis.Lineage, LineageId.Caelith.Value, 1)),
                O("feeling", "Por la intensidad de lo que sentí en cada momento.", "La intensidad se convierte en un reloj imperfecto.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Empathy), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Compassionate), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Theryn.Value, 1)),
                O("promises", "Por las promesas, acuerdos y deudas que dejaron entre nosotros.", "Cada acuerdo ocupa un lugar que no puede intercambiarse.",
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.CommerceAdministration), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Disciplined), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Orveth.Value, 1)),
                O("places", "Por los lugares atravesados y los caminos que los conectaban.", "La memoria se despliega como una ruta.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 3),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.ExplorationSurvival), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1))),

            Q("mortality", "La primera frontera",
                "Algo introduce una idea imposible dentro de tu conciencia:\nla forma que recibirás tendrá un final.", 0f,
                O("weight", "Entonces cada decisión tendrá un peso que antes no tenía.", "La irreversibilidad convierte intención en responsabilidad.",
                    C(FounderScoreAxis.MortalityResponse, "Responsible", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Pragmatic), 2),
                    C(FounderScoreAxis.PoliticalOrientation, nameof(PoliticalOrientationId.Communitarian), 1)),
                O("understand", "Entonces debo comprender ese límite antes de aceptarlo.", "El límite se mantiene delante de ti como una pregunta.",
                    C(FounderScoreAxis.Contemplation, "Analytical", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Curious), 3),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Agnostic), 2)),
                O("others", "Entonces habrá que aprender a permanecer a través de otros.", "La continuidad deja de ser individual.",
                    C(FounderScoreAxis.Attachment, "Collective", 3),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.SocialRelations), 2),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Devout), 1)),
                O("new", "Entonces también será posible comenzar de una forma completamente nueva.", "El final contiene, por primera vez, la idea de un comienzo.",
                    C(FounderScoreAxis.TransformationAcceptance, "Reinvention", 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Bold), 2),
                    C(FounderScoreAxis.SpiritualPosture, nameof(SpiritualPostureId.Skeptical), 1))),

            Q("world", "El mundo te alcanza",
                "Por primera vez algo ajeno al tránsito toca tu conciencia.\nNo tiene voz, pero puede sentirse de varias maneras.\nUna de ellas logra atravesarte con mayor claridad.", 0f,
                O("earth", "Un peso que evita que mis fragmentos se dispersen.", "La presencia sostiene tus fragmentos.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.Earth), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Strength), 1)),
                O("water", "Un flujo que cambia de forma sin perder continuidad.", "La presencia se adapta sin desaparecer.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.Water), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Adaptability), 1)),
                O("fire", "Una temperatura que transforma aquello que toca.", "La presencia altera el borde de tu nueva forma.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.Fire), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Ambitious), 1)),
                O("air", "Una corriente que encuentra una salida donde no parecía existir.", "La presencia convierte el cierre en ruta.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.Air), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 1)),
                O("aether", "Una relación invisible entre fragmentos separados.", "La presencia conecta sin tocar.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.Aether), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Memory), 1)),
                O("none", "Un silencio que no exige adoptar ninguna afinidad.", "La presencia permite que el silencio permanezca.",
                    C(FounderScoreAxis.Element, nameof(ElementalAffinityId.None), 3),
                    C(FounderScoreAxis.Autonomy, "Unbound", 1))),

            Q("perception", "Lo primero que reconoce la nueva forma",
                "Algo comienza a organizarse alrededor de tu conciencia.\nTodavía no es un cuerpo completo.\nSin embargo, una percepción aparece antes que las demás.", 0f,
                O("ardhen", "El peso, la resistencia y el esfuerzo necesario para mover algo.", "La forma aprende esfuerzo antes que movimiento.",
                    C(FounderScoreAxis.Lineage, LineageId.Ardhen.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.Extraction), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Strength), 2)),
                O("eirune", "Los pulsos, heridas y ciclos que mantienen viva una forma.", "La forma reconoce que estar viva exige continuidad.",
                    C(FounderScoreAxis.Lineage, LineageId.Eirune.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.MedicineCare), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Empathy), 2)),
                O("kovari", "Los ritmos, uniones y fallos que permiten desmontar un sistema.", "La forma distingue piezas donde antes solo había totalidad.",
                    C(FounderScoreAxis.Lineage, LineageId.Kovari.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.EngineeringManufacturing), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.ManualPrecision), 2)),
                O("myrven", "Los gestos, contradicciones y significados que existen entre identidades.", "La forma reconoce que un rostro nunca contiene una sola lectura.",
                    C(FounderScoreAxis.Lineage, LineageId.Myrven.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.SocialRelations), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Observation), 2))),

            Q("orientation", "La nueva forma busca orientación",
                "La estructura continúa completándose.\nPara no perderse necesita reconocer una relación fundamental con lo que la rodea.", 0f,
                O("vaelun", "La distancia entre un lugar, un camino y la posibilidad de regresar.", "La forma encuentra dirección en la posibilidad del retorno.",
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.ExplorationSurvival), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 2)),
                O("orveth", "El equilibrio entre aquello que se necesita, se conserva y se entrega.", "La forma reconoce una reserva y su posible destinatario.",
                    C(FounderScoreAxis.Lineage, LineageId.Orveth.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.CommerceAdministration), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Memory), 1)),
                O("caelith", "Las conexiones que permiten convertir fragmentos en conocimiento.", "La forma enlaza observaciones que separadas no bastaban.",
                    C(FounderScoreAxis.Lineage, LineageId.Caelith.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.ResearchEducation), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Observation), 2)),
                O("theryn", "El estado emocional que mantiene unido o separa a un grupo.", "La forma percibe tensión incluso sin conocer todavía a un grupo.",
                    C(FounderScoreAxis.Lineage, LineageId.Theryn.Value, 2),
                    C(FounderScoreAxis.Profession, nameof(ProfessionFamilyId.SocialRelations), 3),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Empathy), 2))),

            Q("threshold", "El umbral se resiste",
                "La salida hacia el plano terrenal comienza a cerrarse.\nNo es una criatura ni una voluntad.\nEs una fuerza que ocupa todo el espacio por el que debes atravesar.", 0f,
                O("support", "Sostener su presión hasta que la abertura vuelva a estabilizarse.", "La abertura tiembla, sostenida por tu resistencia.",
                    C(FounderScoreAxis.CombatStyle, nameof(CombatStyleId.DefensiveSupport), 3),
                    C(FounderScoreAxis.Weapon, nameof(WeaponPreferenceId.Shield), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Patient), 2),
                    C(FounderScoreAxis.RiskProfile, "Measured", 2)),
                O("control", "Fijar límites y obligarla a desplazarse dentro de un espacio controlado.", "El umbral cede dentro de límites que no esperaba.",
                    C(FounderScoreAxis.CombatStyle, nameof(CombatStyleId.TerritorialControl), 3),
                    C(FounderScoreAxis.Weapon, nameof(WeaponPreferenceId.Polearm), 3),
                    C(FounderScoreAxis.LeadershipStyle, "Directive", 2),
                    C(FounderScoreAxis.Control, "Bounded", 2)),
                O("mobility", "Seguir su movimiento hasta encontrar una ruta alrededor.", "La resistencia se convierte en un trayecto.",
                    C(FounderScoreAxis.CombatStyle, nameof(CombatStyleId.Mobility), 3),
                    C(FounderScoreAxis.Weapon, nameof(WeaponPreferenceId.Blade), 2),
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Adaptability), 2)),
                O("precision", "Esperar hasta comprender el patrón exacto de su debilidad.", "El patrón aparece justo antes de desaparecer.",
                    C(FounderScoreAxis.CombatStyle, nameof(CombatStyleId.Precision), 3),
                    C(FounderScoreAxis.Weapon, nameof(WeaponPreferenceId.Ranged), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Cautious), 2)),
                O("assault", "Atravesarla antes de que tenga tiempo de cerrarse por completo.", "La fuerza te alcanza tarde; ya estás al otro lado.",
                    C(FounderScoreAxis.CombatStyle, nameof(CombatStyleId.DirectAssault), 3),
                    C(FounderScoreAxis.Weapon, nameof(WeaponPreferenceId.Heavy), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Bold), 2),
                    C(FounderScoreAxis.RiskProfile, "Bold", 3))),

            Q("ground", "El peso bajo tus pies",
                "Algo aparece debajo de ti.\nTodavía está demasiado lejos para llamarlo suelo.\nPor primera vez comprendes que el impacto podría destruir parte de lo que has conservado.", 0.15f,
                O("clarity", "Proteger la claridad de mi conciencia.", "Tus recuerdos se cierran alrededor de un núcleo estable.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.SelfControl), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Disciplined), 2)),
                O("shared", "Proteger el objeto o fragmento que compartíamos.", "El fragmento ocupa el centro de tu caída.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.ManualPrecision), 2),
                    C(FounderScoreAxis.Attachment, "Keepsake", 3)),
                O("move", "Conservar la capacidad de moverme cuando todo termine.", "La forma reserva movimiento para después del impacto.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Adaptability), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Pragmatic), 2)),
                O("mark", "Dejar una marca que permita reconocer el lugar exacto de mi llegada.", "El punto de caída adquiere una coordenada y una intención.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Curious), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1))),

            Q("unchanged", "Aquello que no debe cambiar",
                "La forma está casi completa.\nTendrá otro rostro, otra voz y necesidades que nunca has conocido.\nSi todo lo demás puede cambiar, algo debe seguir siendo reconocible.", 0.45f,
                O("protect", "Aquello que decido proteger.", "La nueva forma encuentra un límite que está dispuesta a sostener.",
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Protective), 3),
                    C(FounderScoreAxis.LeadershipStyle, "Protective", 2),
                    C(FounderScoreAxis.Lineage, LineageId.Ardhen.Value, 1),
                    C(FounderScoreAxis.Lineage, LineageId.Theryn.Value, 1)),
                O("freedom", "La libertad de elegir en quién puedo convertirme.", "La forma termina de cerrarse sin cerrar tus posibilidades.",
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Independent), 3),
                    C(FounderScoreAxis.Autonomy, "OpenFuture", 3),
                    C(FounderScoreAxis.Lineage, LineageId.Myrven.Value, 1),
                    C(FounderScoreAxis.Lineage, LineageId.Kovari.Value, 1)),
                O("understand", "La necesidad de comprender antes de aceptar una respuesta.", "La pregunta permanece incluso cuando la forma deja de cambiar.",
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Curious), 3),
                    C(FounderScoreAxis.Openness, "Inquiry", 3),
                    C(FounderScoreAxis.Lineage, LineageId.Caelith.Value, 1),
                    C(FounderScoreAxis.Lineage, LineageId.Eirune.Value, 1)),
                O("paths", "La forma en que encuentro caminos incluso después de perderlos.", "El terreno deja de ser una mancha y comienza a parecer un lugar.",
                    C(FounderScoreAxis.Aptitude, nameof(AptitudeId.Orientation), 3),
                    C(FounderScoreAxis.Trait, nameof(PersonalityTraitId.Tenacious), 2),
                    C(FounderScoreAxis.Lineage, LineageId.Vaelun.Value, 1),
                    C(FounderScoreAxis.Lineage, LineageId.Orveth.Value, 1))),
        });

    public static FounderNarrativeQuestion GetQuestion(string id)
    {
        foreach (FounderNarrativeQuestion question in Questions)
        {
            if (question.Id == id) return question;
        }
        throw new ArgumentOutOfRangeException(nameof(id), id, "Unknown narrative question.");
    }

    private static FounderNarrativeQuestion Q(
        string id,
        string title,
        string text,
        float reveal,
        params FounderNarrativeChoice[] choices) =>
        new(id, title, text, Array.AsReadOnly(choices), reveal);

    private static FounderNarrativeChoice O(
        string id,
        string text,
        string consequence,
        params ScoreContribution[] scores) =>
        new(id, text, consequence, Array.AsReadOnly(scores), consequence);

    private static FounderNarrativeChoice O(
        string id,
        string text,
        string consequence,
        string prologue,
        params ScoreContribution[] scores) =>
        new(id, text, consequence, Array.AsReadOnly(scores), prologue);

    private static ScoreContribution C(
        FounderScoreAxis axis,
        string value,
        int weight) =>
        new(axis, value, weight);
}
